# Generated by Django 5.2.17 on 2026-09-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office'),
        ),
    ]
