# Generated by Django 5.2.17 on 2026-09-16 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('document_number', models.CharField(max_length=120, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('status', models.CharField(choices=[('VALID', 'VALID'), ('INVALID', 'INVALID'), ('REVOKED', 'REVOKED'), ('EXPIRED', 'EXPIRED')], default='VALID', max_length=20)),
                ('issuing_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offices.office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
