# Generated by Django 5.2.17 on 2026-09-16 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NEWS_VIEW', 'News view'), ('ISSUANCE_DOWNLOAD', 'Issuance download'), ('RESOURCE_DOWNLOAD', 'Resource download'), ('SEARCH', 'Portal search'), ('DIRECTORY_VISIT', 'School-directory visit'), ('SCHOOL_VIEW', 'School profile view')], db_index=True, max_length=30)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
