# Generated by Django 5.2.17 on 2026-09-16 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MEMO', 'Division Memorandum'), ('ORDER', 'Division Order'), ('ADVISORY', 'Advisory'), ('CIRCULAR', 'Circular'), ('OTHER', 'Other')], max_length=30)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField()),
                ('date_issued', models.DateField()),
                ('pdf', models.FileField(upload_to='issuances/')),
                ('status', models.CharField(default='PUBLISHED', max_length=20)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
