# Generated by Django 5.2.17 on 2026-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='category',
            field=models.CharField(choices=[('DIVISION_MEMO', 'Division Memo'), ('OFFICE_MEMO', 'Office Memo'), ('UNNUMBERED_MEMO', 'Unnumbered Memo'), ('DIVISION_ADVISORY', 'Division Advisory'), ('DEPED_ORDER', 'DepEd Order'), ('DEPED_MEMORANDUM', 'DepEd Memorandum'), ('DEPED_ADVISORY', 'DepEd Advisory'), ('CIRCULAR', 'Circular'), ('GUIDELINE', 'Guideline'), ('POLICY', 'Policy'), ('NOTICE', 'Official Notice'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
