# Generated by Django 5.2.17 on 2026-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0003_issuance_created_by_alter_issuance_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuance',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuance',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
