# Generated by Django 5.2.17 on 2026-09-16 16:35

import issuances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0004_issuance_archived_issuance_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=issuances.models.issuance_cover_upload),
        ),
    ]
