# Generated by Django 5.2.17 on 2026-09-16 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('school_type', models.CharField(blank=True, max_length=80)),
                ('level', models.CharField(blank=True, max_length=80)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=20)),
                ('school_head', models.CharField(blank=True, max_length=160)),
                ('address', models.TextField(blank=True)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('student_population', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher_population', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='offices.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
