# Generated by Django 5.2.17 on 2026-09-16 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=100)),
                ('salary_grade', models.CharField(blank=True, max_length=50)),
                ('qualification', models.TextField()),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('training', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('requirements', models.TextField()),
                ('posting_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offices.office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
