# Generated by Django 5.2.17 on 2026-09-16 13:59

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=content.models.public_upload)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office'),
        ),
        migrations.AddField(
            model_name='download',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office'),
        ),
        migrations.AddField(
            model_name='news',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=content.models.public_upload),
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(upload_to=content.models.public_upload),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=content.models.public_upload),
        ),
    ]
