# Generated by Django 5.2.17 on 2026-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_announcement_expires_at_download_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='source_imported_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional link to the original Facebook post.', max_length=1000, verbose_name='Facebook source link'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_imported_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional link to the original Facebook post.', max_length=1000, verbose_name='Facebook source link'),
        ),
    ]
