# Generated by Django 5.2.17 on 2026-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_announcement_source_imported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='facebook_post_id',
            field=models.CharField(blank=True, editable=False, max_length=160, null=True, unique=True),
        ),
    ]
