# Generated by Django 5.2.17 on 2026-09-17 03:57

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_seed_citizens_charter'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='document',
            field=models.FileField(blank=True, upload_to=content.models.public_upload),
        ),
    ]
